application: rhinedoll
version: 0-0-1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
  script: server.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: latest